apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels:
    label-name:   cimagecode


spec:
  containers:
    - image: farouk582/farouk2023040169
      name: c4
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"  